@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@accToken = 

### Create Author
POST http://{{host}}/api/authors
Content-Type: application/json

{
    "name": "test",
    "link": "test",
    "bio": "test",
    "description": "test"
}

### Find All Author
GET http://{{host}}/api/authors HTTP/1.1

### Find Author By ID
GET http://{{host}}/api/authors/-yyCeRZpAZLI HTTP/1.1

### Find Author By Slug
GET http://{{host}}/api/authors/slug/william-sloane-coffin HTTP/1.1

### Find Author And Quotes
GET http://{{host}}/api/authors/ropvZKOXYhLr/quotes HTTP/1.1
