### Opening
GET http://localhost:3000/
Accept: application/json
Content-Type: application/json

### Create Quote
POST http://localhost:3000/api/quotes
Accept: application/json
Content-Type: application/json

{
    "author_id": "pY4cjNm7ogoc",
    "content": "asd"
}

### Find Quote By ID
GET http://localhost:3000/api/quotes/LVmRBE6cytXv
Accept: application/json
Content-Type: application/json

### Get Random Quote
GET http://localhost:3000/api/random
Accept: application/json
Content-Type: application/json

### Get All Quotes
GET http://localhost:3000/api/quotes
Accept: application/json
Content-Type: application/json

# ================================================================================================================

### Create Author
POST http://localhost:3000/api/authors
Accept: application/json
Content-Type: application/json

{
    "name": "asd",
    "link": "asd",
    "bio": "asd",
    "description": "asd",
    "quote_count":
}

### Find Author By ID
GET http://localhost:3000/api/authors/-yyCeRZpAZLI
Accept: application/json
Content-Type: application/json

### Find All Author
GET http://localhost:3000/api/authors
Accept: application/json
Content-Type: application/json