### Opening
GET http://localhost:3000/

### Create Quote
POST http://localhost:3000/api/quotes
Accept: application/json
Content-Type: application/json

{
    "author_id": "pY4cjNm7ogoc",
    "content": "test"
}

### Get All Quotes
GET http://localhost:3000/api/quotes

### Get All Quotes With Filters
GET http://localhost:3000/api/quotes?min-length=10&max-length=30&limit=2&offset=2

### Find Quote By ID
GET http://localhost:3000/api/quotes/LVmRBE6cytXv

### Find Quote And Author
GET http://localhost:3000/api/quotes/LVmRBE6cytXv/author

### Get Random Quote
GET http://localhost:3000/api/quotes/random-quote

### Get Random Quote And Author
GET http://localhost:3000/api/quotes/random-quote/author

# ==================================================

### Create Author
POST http://localhost:3000/api/authors
Accept: application/json
Content-Type: application/json

{
    "name": "test",
    "link": "test",
    "bio": "test",
    "description": "test"
}

### Find All Author
GET http://localhost:3000/api/authors

### Find Author By ID
GET http://localhost:3000/api/authors/-yyCeRZpAZLI

### Find Author By Slug
GET http://localhost:3000/api/authors/slug/william-sloane-coffin

### Find Author And Quotes
GET http://localhost:3000/api/authors/ropvZKOXYhLr/quotes

# ==================================================

### Create Quote Tag
POST http://localhost:3000/api/quote-tags
Accept: application/json
Content-Type: application/json

{
    "name": "test"
}

### Find All Quote Tag
GET http://localhost:3000/api/quote-tags

### Find Quote Tag By ID
GET http://localhost:3000/api/quote-tags/fvpORe-t

### Delete Quote Tag
DELETE  http://localhost:3000/api/quote-tags

{
    "id": "e61e09eb-f2b",
    "name": "test"
}
